apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockereks
  labels:
    app: dockereks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockereks
  template:
    metadata:
      labels:
        app: dockereks
    spec:
      containers:
        - name: dockereks
          image: 879409995620.dkr.ecr.ap-southeast-2.amazonaws.com/dockereks:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080